name: Npm Publish

on:
  release:
    types: [published]

jobs:    
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org/
      - run: npm ci
      - run: npm run build ngx-date-input
      - run: npm publish dist/ngx-date-input --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}

  publish-gpr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 18
          registry-url: https://npm.pkg.github.com/
      - run: npm ci
      - run: npm run build ngx-date-input
      - run: npm publish dist/ngx-date-input
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
